import type { FC } from "react";

import Head from "next/head";
import DashboardEnvironment from "@/components/environments/Dashboard";

const Dashboard: FC = () => {
  return (
    <>
      <Head>
        <title>next-ui</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardEnvironment />
    </>
  );
};

export default Dashboard;
