import type { FC } from "react";
import Head from "next/head";
import IndexEnvironment from "@/components/environments/Index";

const Index: FC = () => {
  return (
    <>
      <Head>
        <title>next-ui</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <IndexEnvironment />
    </>
  );
};

export default Index;
