import type { FC } from "react";
import Head from "next/head";
import Logo from "@/components/atoms/Logo";

const LogoPage: FC = () => {
  return (
    <>
      <Head>
        <title>Ichimatsu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container w-auto text-center align-middle">
        <div className="my-20">
          <Logo />
        </div>
      </main>
    </>
  );
};

export default LogoPage;
