import type { FC } from "react";
import Head from "next/head";
import MintEnvironment from "@/components/environments/Mint";

const Mint: FC = () => {
  return (
    <>
      <Head>
        <title>Mint | Ichimatsu</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MintEnvironment />
    </>
  );
};

export default Mint;
